version: "3"

services:
  ozzolum-website:
    container_name: ozzolum-website
    image: node:12
    build: .
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - /var/ozzolum-website/.env:/ozzolum-website/.env
      - /var/ozzolum-website/public.pem:/ozzolum-website/public.pem
      - /var/ozzolum-website/private.key:/ozzolum-website/private.key